process.env.NODE_ENV = 'test'
process.env.PORT = '3002'
process.env.DB_HOST = 'localhost'
process.env.DB_PORT = '5436'
process.env.DB_USERNAME = 'docker'
process.env.DB_PASSWORD = 'docker'
process.env.DB_DATABASE = 'products'
process.env.JWT_SECRET = 'products-service-e2e-secret'
