process.env.NODE_ENV = 'test'
process.env.PORT = '3003'
process.env.DB_HOST ||= 'localhost'
process.env.DB_PORT ||= '5433'
process.env.DB_USERNAME ||= 'docker'
process.env.DB_PASSWORD ||= 'docker'
process.env.DB_DATABASE ||= 'checkout'
process.env.JWT_SECRET = 'checkout-service-e2e-secret'
